### ISSUE TITLE
phhwConfig.h not found during install

### ISSUE THREAD

**Issue by mdurruty** [svvitale/nxppy#69] opened 2018-02-13 09:08 UTC
I use:
* Ubuntu 16.04
* Python3.5.2
* SPI is enabled

`pip install nxppy ` leads to the error  `phhwConfig.h: No such file or directory`.
I have the same error while installing from the sources. 
Thank you for your help. 

My logs below : 

## username@my-VirtualBox:~$ sudo apt-get install build-essential cmake python3-dev unzip wget
[sudo] password for username: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
python3-dev is already the newest version (3.5.1-3).
unzip is already the newest version (6.0-20ubuntu1).
cmake is already the newest version (3.5.1-1ubuntu3).
wget is already the newest version (1.17.1-1ubuntu1.3).
0 upgraded, 0 newly installed, 0 to remove and 247 not upgraded.

##  username@my-VirtualBox:~$ pip install nxppy
Collecting nxppy
  Using cached nxppy-1.5.1.tar.gz
Building wheels for collected packages: nxppy
  Running setup.py bdist_wheel for nxppy ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-08i1927z/nxppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpf1huodqupip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  compiling NxpRdLib
  [Downloading NXP Reader Library]
  --2018-02-13 09:57:39--  https://nxp1.sharepoint.com/sites/6_1/S&CExternal/_layouts/15/guestaccess.aspx?docid=0afe70cb96bba406d9c3c27534d03087d&authkey=AU04PywGBtgqJtk4Fp0GT0M
  Resolving nxp1.sharepoint.com (nxp1.sharepoint.com)... 104.146.132.28
  Connecting to nxp1.sharepoint.com (nxp1.sharepoint.com)|104.146.132.28|:443... connected.
  HTTP request sent, awaiting response... 200 OK
  Length: 22269 (22K) [text/html]
  Saving to: ‘nxp.zip’
  
       0K .......... .......... .                               100%  576K=0,04s
  
  2018-02-13 09:57:40 (576 KB/s) - ‘nxp.zip’ saved [22269/22269]
  
  [nxp.zip]
    End-of-central-directory signature not found.  Either this file is not
    a zipfile, or it constitutes one disk of a multi-part archive.  In the
    latter case the central directory and zipfile comment will be found on
    the last disk(s) of this archive.
  unzip:  cannot find zipfile directory in one of nxp.zip or
          nxp.zip.zip, and cannot find nxp.zip.ZIP, period.
  ./get_nxpRdLib.sh: line 17: pushd: nxp/build: No such file or directory
  CMake Error: The source directory "/tmp/pip-build-08i1927z" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  make: *** No rule to make target 'NxpRdLibLinuxPN512'.  Stop.
  ./get_nxpRdLib.sh: line 20: popd: directory stack empty
  building 'nxppy' extension
  creating build
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DLINUX -DNATIVE_C_CODE -DNXPBUILD_CUSTOMER_HEADER_INCLUDED -DNXPBUILD__PHHAL_HW_RC523 -I/usr/include/python3.5m -c Mifare.c -o build/temp.linux-x86_64-3.5/Mifare.o -O0 -std=gnu99 -isystemnxp/nxprdlib/NxpRdLib/intfs -isystemnxp/nxprdlib/NxpRdLib/types -isystemnxp/nxprdlib/NxpRdLib -isystemnxp/linux/intfs -isystemnxp/linux/comps/phbalReg/src/Linux -isystemnxp/linux/shared -isystemnxp/examples/NfcrdlibEx4_MIFAREClassic/intfs -isystemnxp/nxprdlib/NxpRdLib/comps/phbalReg/src/Stub -isystemnxp/linux/comps/phPlatform/src/Posix -isystemnxp/linux/comps/phOsal/src/Posix
  In file included from Mifare.c:1:0:
  Mifare.h:32:24: fatal error: phhwConfig.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for nxppy
  Running setup.py clean for nxppy
Failed to build nxppy
Installing collected packages: nxppy
  Running setup.py install for nxppy ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-08i1927z/nxppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-uo098cun-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    compiling NxpRdLib
    [Downloading NXP Reader Library]
    --2018-02-13 09:57:41--  https://nxp1.sharepoint.com/sites/6_1/S&CExternal/_layouts/15/guestaccess.aspx?docid=0afe70cb96bba406d9c3c27534d03087d&authkey=AU04PywGBtgqJtk4Fp0GT0M
    Resolving nxp1.sharepoint.com (nxp1.sharepoint.com)... 104.146.132.28
    Connecting to nxp1.sharepoint.com (nxp1.sharepoint.com)|104.146.132.28|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 22269 (22K) [text/html]
    Saving to: ‘nxp.zip’
    
         0K .......... .......... .                               100%  591K=0,04s
    
    2018-02-13 09:57:42 (591 KB/s) - ‘nxp.zip’ saved [22269/22269]
    
    [nxp.zip]
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of nxp.zip or
            nxp.zip.zip, and cannot find nxp.zip.ZIP, period.
    ./get_nxpRdLib.sh: line 17: pushd: nxp/build: No such file or directory
    CMake Error: The source directory "/tmp/pip-build-08i1927z" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    make: *** No rule to make target 'NxpRdLibLinuxPN512'.  Stop.
    ./get_nxpRdLib.sh: line 20: popd: directory stack empty
    building 'nxppy' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DLINUX -DNATIVE_C_CODE -DNXPBUILD_CUSTOMER_HEADER_INCLUDED -DNXPBUILD__PHHAL_HW_RC523 -I/usr/include/python3.5m -c Mifare.c -o build/temp.linux-x86_64-3.5/Mifare.o -O0 -std=gnu99 -isystemnxp/nxprdlib/NxpRdLib/intfs -isystemnxp/nxprdlib/NxpRdLib/types -isystemnxp/nxprdlib/NxpRdLib -isystemnxp/linux/intfs -isystemnxp/linux/comps/phbalReg/src/Linux -isystemnxp/linux/shared -isystemnxp/examples/NfcrdlibEx4_MIFAREClassic/intfs -isystemnxp/nxprdlib/NxpRdLib/comps/phbalReg/src/Stub -isystemnxp/linux/comps/phPlatform/src/Posix -isystemnxp/linux/comps/phOsal/src/Posix
    In file included from Mifare.c:1:0:
    Mifare.h:32:24: fatal error: phhwConfig.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-08i1927z/nxppy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-uo098cun-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-08i1927z/nxppy/

**Comment by svvitale** [comment] 2018-02-13 15:38
Duplicate of #55

**Closed by svvitale** 2018-02-13 15:38 UTC
