### ISSUE TITLE
Error at installation of xnppy 

### ISSUE THREAD

**Issue by sabberlatz** [svvitale/nxppy#67] opened 2018-01-24 15:35 UTC
Please answer these questions as part of your new issue.

##### Which version of Python are you using?
2.7 and 3

##### Which OS and version are you running?
Jessie and Stretch
##### Is SPI enabled?
sure :-)
##### Are you trying to read/write a Mifare Classic card?  (This is currently unsupported)
yes

HI, I have difficulties installing xnppy. I already updated and upgraded the RPi, installed python-dev but the error (on Jessie and Stretch) is always the same. 
But first one question: Is xnppy running on Stretch too?

Here the hardcopy:

======================================================
pi@raspberrypi:~ $ pip install nxppy
Downloading/unpacking nxppy
  Downloading nxppy-1.5.1.tar.gz
  Running setup.py (path:/tmp/pip-build-taj8hE/nxppy/setup.py) egg_info for package nxppy
    
Installing collected packages: nxppy
  Running setup.py install for nxppy
    compiling NxpRdLib
    [Downloading NXP Reader Library]
    --2018-01-24 15:29:07--  https://nxp1.sharepoint.com/sites/6_1/S&CExternal/_layouts/15/guestaccess.aspx?docid=0afe70cb96bba406d9c3c27534d03087d&authkey=AU04PywGBtgqJtk4Fp0GT0M
    Resolving nxp1.sharepoint.com (nxp1.sharepoint.com)... 13.107.6.151
    Connecting to nxp1.sharepoint.com (nxp1.sharepoint.com)|13.107.6.151|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 21586 (21K) [text/html]
    Saving to: ‘nxp.zip’
    
         0K .......... .......... .                               100% 7.40M=0.003s
    
    2018-01-24 15:29:08 (7.40 MB/s) - ‘nxp.zip’ saved [21586/21586]
    
    [nxp.zip]
      End-of-central-directory signature not found.  Either this file is not
      a zipfile, or it constitutes one disk of a multi-part archive.  In the
      latter case the central directory and zipfile comment will be found on
      the last disk(s) of this archive.
    unzip:  cannot find zipfile directory in one of nxp.zip or
            nxp.zip.zip, and cannot find nxp.zip.ZIP, period.
    ./get_nxpRdLib.sh: line 17: pushd: nxp/build: No such file or directory
    CMake Error: The source directory "/tmp/pip-build-taj8hE" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    make: *** No rule to make target 'NxpRdLibLinuxPN512'.  Stop.
    ./get_nxpRdLib.sh: line 20: popd: directory stack empty
    building 'nxppy' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DLINUX -DNATIVE_C_CODE -DNXPBUILD_CUSTOMER_HEADER_INCLUDED -DNXPBUILD__PHHAL_HW_RC523 -I/usr/include/python2.7 -c Mifare.c -o build/temp.linux-armv7l-2.7/Mifare.o -O0 -std=gnu99 -isystemnxp/nxprdlib/NxpRdLib/intfs -isystemnxp/nxprdlib/NxpRdLib/types -isystemnxp/nxprdlib/NxpRdLib -isystemnxp/linux/intfs -isystemnxp/linux/comps/phbalReg/src/Linux -isystemnxp/linux/shared -isystemnxp/examples/NfcrdlibEx4_MIFAREClassic/intfs -isystemnxp/nxprdlib/NxpRdLib/comps/phbalReg/src/Stub -isystemnxp/linux/comps/phPlatform/src/Posix -isystemnxp/linux/comps/phOsal/src/Posix
    In file included from Mifare.c:1:0:
    Mifare.h:32:24: fatal error: phhwConfig.h: No such file or directory
     #include <phhwConfig.h>
                            ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-taj8hE/nxppy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DtTyqE-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_ext

compiling NxpRdLib

[Downloading NXP Reader Library]

--2018-01-24 15:29:07--  https://nxp1.sharepoint.com/sites/6_1/S&CExternal/_layouts/15/guestaccess.aspx?docid=0afe70cb96bba406d9c3c27534d03087d&authkey=AU04PywGBtgqJtk4Fp0GT0M

Resolving nxp1.sharepoint.com (nxp1.sharepoint.com)... 13.107.6.151

Connecting to nxp1.sharepoint.com (nxp1.sharepoint.com)|13.107.6.151|:443... connected.

HTTP request sent, awaiting response... 200 OK

Length: 21586 (21K) [text/html]

Saving to: ‘nxp.zip’

     0K .......... .......... .                               100% 7.40M=0.003s

2018-01-24 15:29:08 (7.40 MB/s) - ‘nxp.zip’ saved [21586/21586]

[nxp.zip]

  End-of-central-directory signature not found.  Either this file is not

  a zipfile, or it constitutes one disk of a multi-part archive.  In the

  latter case the central directory and zipfile comment will be found on

  the last disk(s) of this archive.

unzip:  cannot find zipfile directory in one of nxp.zip or

        nxp.zip.zip, and cannot find nxp.zip.ZIP, period.

./get_nxpRdLib.sh: line 17: pushd: nxp/build: No such file or directory

CMake Error: The source directory "/tmp/pip-build-taj8hE" does not appear to contain CMakeLists.txt.

Specify --help for usage, or press the help button on the CMake GUI.

make: *** No rule to make target 'NxpRdLibLinuxPN512'.  Stop.

./get_nxpRdLib.sh: line 20: popd: directory stack empty

building 'nxppy' extension

creating build

creating build/temp.linux-armv7l-2.7

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DLINUX -DNATIVE_C_CODE -DNXPBUILD_CUSTOMER_HEADER_INCLUDED -DNXPBUILD__PHHAL_HW_RC523 -I/usr/include/python2.7 -c Mifare.c -o build/temp.linux-armv7l-2.7/Mifare.o -O0 -std=gnu99 -isystemnxp/nxprdlib/NxpRdLib/intfs -isystemnxp/nxprdlib/NxpRdLib/types -isystemnxp/nxprdlib/NxpRdLib -isystemnxp/linux/intfs -isystemnxp/linux/comps/phbalReg/src/Linux -isystemnxp/linux/shared -isystemnxp/examples/NfcrdlibEx4_MIFAREClassic/intfs -isystemnxp/nxprdlib/NxpRdLib/comps/phbalReg/src/Stub -isystemnxp/linux/comps/phPlatform/src/Posix -isystemnxp/linux/comps/phOsal/src/Posix

In file included from Mifare.c:1:0:

Mifare.h:32:24: fatal error: phhwConfig.h: No such file or directory

 #include <phhwConfig.h>

                        ^
compilation terminated.

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

**### Cleaning up...
**Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-taj8hE/nxppy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DtTyqE-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-taj8hE/nxppy**
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 15: ordinal not in range(128)
============================================================**

**Comment by svvitale** [comment] 2018-01-24 16:03
Duplicate of #55

**Closed by svvitale** 2018-01-24 16:03 UTC
