### ISSUE TITLE
1k MIFARE ISO14443A 13.56mhz NFC S50 Tag

### ISSUE THREAD

**Issue by toby314** [svvitale/nxppy#9] opened 2015-03-06 09:26 UTC
hi,
I know you are just working on the Ultralights.
are there any plans to get others working?

reading the uid and then writing to 4 bytes to block 10 gives:
uid = 9071F96B
nxppy.WriteError: Write failed: 201

**Comment by svvitale** [comment] 2015-03-09 20:39
Yes, you can't read or write Mifare 1k cards without authenticating first (see http://www.nxp.com/documents/application_note/AN1304.pdf).  This is a duplicate of #5.  Please read through that issue for a full description of our strategy.  If you'd like to contribute via a pull request, I'm more than happy to incorporate the code.

**Closed by svvitale** 2015-03-09 20:39 UTC
